// Generated by CoffeeScript 1.2.1-pre
var Tutor;

Tutor = (function() {

  Tutor.name = 'Tutor';

  function Tutor() {
    this.dvorakMap = {
      '"': '_',
      "'": '-',
      '+': '}',
      '-': '[',
      ',': 'w',
      '/': 'z',
      '.': 'v',
      ';': 's',
      ':': 'S',
      '=': ']',
      '<': 'W',
      '?': 'Z',
      '>': 'V',
      'C': 'J',
      'B': 'X',
      'E': '>',
      'D': 'E',
      'G': 'I',
      'F': 'U',
      'I': 'C',
      'H': 'D',
      'K': 'T',
      'J': 'H',
      'L': 'N',
      'O': 'R',
      'N': 'B',
      'Q': '"',
      'P': 'L',
      'S': 'O',
      'R': 'P',
      'U': 'G',
      'T': 'Y',
      'W': '<',
      'V': 'K',
      'Y': 'F',
      'X': 'Q',
      '[': '/',
      'Z': ':',
      ']': '=',
      '_': '{',
      'c': 'j',
      'b': 'x',
      'e': '.',
      'd': 'e',
      'g': 'i',
      'f': 'u',
      'i': 'c',
      'h': 'd',
      'k': 't',
      'j': 'h',
      'l': 'n',
      'o': 'r',
      'n': 'b',
      'q': "'",
      'p': 'l',
      's': 'o',
      'r': 'p',
      'u': 'g',
      't': 'y',
      'w': ',',
      'v': 'k',
      'y': 'f',
      'x': 'q',
      '{': '?',
      'z': ';',
      '}': '+'
    };
  }

  Tutor.prototype.swap = function(a, b) {
    var content;
    content = b.html();
    b.html(a.html());
    return a.html(content);
  };

  Tutor.prototype.rearrangeQwertyToDvorak = function(keys) {};

  Tutor.prototype.start = function($canvas) {
    var canvas, context, x, y;
    canvas = $canvas[0];
    canvas.width = $canvas.width();
    canvas.height = $canvas.height();
    context = canvas.getContext('2d');
    x = 150;
    y = 100;
    context.font = "40pt Calibri";
    context.fillStyle = "#0000ff";
    return context.fillText("Hello World!", x, y);
  };

  return Tutor;

})();
