// Generated by CoffeeScript 1.2.1-pre
var Tutor;

Tutor = (function() {
  var dvorakMap;

  Tutor.name = 'Tutor';

  function Tutor() {}

  dvorakMap = {
    '"': '_',
    "'": '-',
    '+': '}',
    '-': '[',
    ',': 'w',
    '/': 'z',
    '.': 'v',
    ';': 's',
    ':': 'S',
    '=': ']',
    '<': 'W',
    '?': 'Z',
    '>': 'V',
    'C': 'J',
    'B': 'X',
    'E': '>',
    'D': 'E',
    'G': 'I',
    'F': 'U',
    'I': 'C',
    'H': 'D',
    'K': 'T',
    'J': 'H',
    'L': 'N',
    'O': 'R',
    'N': 'B',
    'Q': '"',
    'P': 'L',
    'S': 'O',
    'R': 'P',
    'U': 'G',
    'T': 'Y',
    'W': '<',
    'V': 'K',
    'Y': 'F',
    'X': 'Q',
    '[': '/',
    'Z': ':',
    ']': '=',
    '_': '{',
    'c': 'j',
    'b': 'x',
    'e': '.',
    'd': 'e',
    'g': 'i',
    'f': 'u',
    'i': 'c',
    'h': 'd',
    'k': 't',
    'j': 'h',
    'l': 'n',
    'o': 'r',
    'n': 'b',
    'q': "'",
    'p': 'l',
    's': 'o',
    'r': 'p',
    'u': 'g',
    't': 'y',
    'w': ',',
    'v': 'k',
    'y': 'f',
    'x': 'q',
    '{': '?',
    'z': ';',
    '}': '+'
  };

  return Tutor;

})();
